<?php

use Illuminate\Database\Seeder;
use App\Role;
use App\User;
class ParticipantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    $participantRole = Role::where('name', 'participant')->first();

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '11012410';
    $participant->name = 'Agus Sari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Sun Plasa';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285275304288';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'saribmj.90@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '14011448';
    $participant->name = 'Raja Gries Sheilla Moren';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Mall SKA';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628117688000';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'mooranye@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '15009514';
    $participant->name = 'Shena Giantasya';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Bandung Banda';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811212211';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'giantasya_shena@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '15009857';
    $participant->name = 'Yani Dewi Erinesari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Semarang Mall Ciputra';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628112799959';
    $participant->gender = 'Female';
    $participant->region = 'Jateng';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'yd.erenesari@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '12009738';
    $participant->name = 'Sayu Putu Okoningrum Loestiani';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Denpasar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281239345847';
    $participant->gender = 'Female';
    $participant->region = 'BaliNusra';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'CHOCOLATECAKICAKI@GMAIL.COM';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '14010236';
    $participant->name = 'Andi Lana Andayani';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Gorontalo';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811439934';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'LANASIOUSLY@GMAIL.COM';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '15009059';
    $participant->name = 'Novita Sari';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Wahidin';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285359983392';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'NOVITA201092@GMAIL.COM';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '15008395';
    $participant->name = 'Silvia Ardita';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Balaraja';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811169000';
    $participant->gender = 'Female';
    $participant->region = 'West Jakarta';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'silviaardita23@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '15011707';
    $participant->name = 'Nindya Devi Mentari';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'BEC';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628112230046';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'nindyadm@yahoo.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '15010301';
    $participant->name = 'Anggita Primanti Esthiningtyas';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Jogja City Mall';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281222702505';
    $participant->gender = 'Female';
    $participant->region = 'Jateng';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'anggiianggitaa6@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '15011645';
    $participant->name = 'Futih';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Mojokerto';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6282234262119';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'futi.aljufry@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '13008704';
    $participant->name = 'Rina Puspita Sari';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Nunukan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285250851111';
    $participant->gender = 'Female';
    $participant->region = 'Kalimantan';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'midoryphyta@yahoo.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '14008185';
    $participant->name = 'Ni Made Diah Septiarini Putri';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Kuta';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628113999996';
    $participant->gender = 'Female';
    $participant->region = 'BaliNusra';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'dyahsputri@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '16009100';
    $participant->name = 'Dewanti Pratiwi Asyari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Kendari';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811402704';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'DEWAND27@GMAIL.COM';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '68210';
    $participant->name = 'Elvitrika Shanty';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Cibubur';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811950818';
    $participant->gender = 'Female';
    $participant->region = 'East Jakarta';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'elvitrika_shanty@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '80215';
    $participant->name = 'Emira Intan Emmyr Moeis';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Tasikmalaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811230306';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'emira_ie_moeis@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '78234';
    $participant->name = 'Sri Wulandari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Probolinggo';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '811370049';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'sri_wulandari@telkomsel.co.id; wulan2010@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '79161';
    $participant->name = 'Dewi M. Sari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Semarang Mall Ciputra';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628122668880';
    $participant->gender = 'Female';
    $participant->region = 'Jateng';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'dewi_m_sari@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '78253';
    $participant->name = 'Ervina Lesmonowati';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Tarakan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811530018';
    $participant->gender = 'Female';
    $participant->region = 'Kalimantan';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'vina.ndcie@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '70258';
    $participant->name = 'Alfiani Mansyur';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811414545';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'Alfiani_Mansyur@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '16009908';
    $participant->name = 'Novi Eldiarti Simatupang';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285275565690';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'novieldiarti@yahoo.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '11009802';
    $participant->name = 'Novita Putri';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285287909873';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'putri.novita20@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '15010234';
    $participant->name = 'Siti Nurhasanah';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6282219216171';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'sitinurhasanh28@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '16009615';
    $participant->name = 'Lia Marliana';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285220666001';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'lia.maharani2014@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '10092697';
    $participant->name = 'Astri Mega T';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281230870152';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'terataifunair@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '11009560';
    $participant->name = 'Haslinda Hasan';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281354719139';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'indah_the81@yahoo.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '09011778';
    $participant->name = 'Rizki Ivo Deswita';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281361100478';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'ivodeswita@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '14008314';
    $participant->name = 'Margahayu';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628113111310';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'bundamitra79@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '14013219';
    $participant->name = 'Fitri Kasanti';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628111788098';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'fitrikasanti@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '15006312';
    $participant->name = 'Nur Irma Santi';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285242844473';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'nurirmasantifh@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '14008306';
    $participant->name = 'Nurhalima';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285395879225';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'nurhalima90@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '007406';
    $participant->name = 'Fanny Prina';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628112200247';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'huani.1102@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '10009790';
    $participant->name = 'Fitriani';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285299484543';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'fitrianihalo@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '10012233';
    $participant->name = 'Ully Maemuna';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811444122';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'ully.maemuna001@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '13009197';
    $participant->name = 'Selli Karlinawati';
    $participant->unit_type = 'Ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281290846824';
    $participant->gender = 'Female';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'karlinawatiselli@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '13009491';
    $participant->name = 'Hernita Gurusinga';
    $participant->unit_type = 'Ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628111103400';
    $participant->gender = 'Female';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'hernita.gurusinga@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '15009036';
    $participant->name = 'Josephine Sarti Kanan';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sulawesi';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628113951990';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'josephinebunga@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '73273';
    $participant->name = 'Laili Asnia';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sumbagsel';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811740015';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagsel';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'laili_asnia@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '70273';
    $participant->name = 'Hetty  Haryatiningsih';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Central Jakarta';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811125070';
    $participant->gender = 'Female';
    $participant->region = 'Central Jakarta';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'hetty_haryatiningsih@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '80035';
    $participant->name = 'Herny Damayani';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Jabar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811102309';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'hernydamayani@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '86003';
    $participant->name = 'Dewi Anggraeny';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Jateng';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628113315005';
    $participant->gender = 'Female';
    $participant->region = 'Jateng';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'dewi_anggraeny@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '70020';
    $participant->name = 'Idhawati Kusumaningtyas';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sulawesi';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811370006';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'idhawati_kusumaningtyas@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '15011544';
    $participant->name = 'Ardy Putra';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Central Park';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281294005266';
    $participant->gender = 'Male';
    $participant->region = 'West Jakarta';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'ardyyputraa@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 1;
    $participant->nik = '14009965';
    $participant->name = 'Heryansa';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Samarinda';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628115805800';
    $participant->gender = 'Male';
    $participant->region = 'Kalimantan';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'Heryansa88@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '13010804';
    $participant->name = 'M. Arief Syahputra Harahap';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Krakatau';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281370726927';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'arief_syahputra@ymail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 2;
    $participant->nik = '13010539';
    $participant->name = 'Imam Nurdiansah';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Singkawang';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285310454080';
    $participant->gender = 'Male';
    $participant->region = 'Kalimantan';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'imamtpr@yahoo.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '11011904';
    $participant->name = 'Erwin Casanova Sembiring';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Medan Sun Plasa';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628116912345';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'erwin_casanova@ymail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '12008332';
    $participant->name = 'Calvin';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Pekanbaru';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628117525809';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'calvin.wongso90@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '12009187';
    $participant->name = 'Pipih Septina';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Bandung Dago';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281313651168';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'pipih.septina@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '14009843';
    $participant->name = 'Delly Indrawan';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Bandung Banda';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811207979';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'delly.indrawan@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '15010600';
    $participant->name = 'Rizky Romadhon Wicaksono';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Gresik';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628113199990';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'AgentOfGaruda@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 7;
    $participant->nik = '15009314';
    $participant->name = 'Gede Kusna Wira Kusuma';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285343899808';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'cuzna92@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '82249';
    $participant->name = 'Sutresno';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Padang';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811750025';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'sutresno@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 11;
    $participant->nik = '72337';
    $participant->name = 'Rezekinta';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Kisaran';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811610052';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'rezekinta@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '15009728';
    $participant->name = 'Josef Kusuma Rahardjo';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628113305353';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'josef.kusuma.rahardjo@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 3;
    $participant->nik = '13011589';
    $participant->name = 'Primantho Roy';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285255504383';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = ' primanthoroy@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '14011451';
    $participant->name = 'Hendra Putra Hutagaol';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281397337770';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'putragaol@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '13011630';
    $participant->name = 'Riski Jianur';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628112222596';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'riskijianur@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 4;
    $participant->nik = '15011613';
    $participant->name = 'Irfan Supriyadi';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285294464657';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'irfansupriyadi44@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '003735';
    $participant->name = 'Katon Sukmono';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628126532601';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'katonsukmono@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '15008351';
    $participant->name = 'Rollowe Sembiring';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285297428008';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = ' rollowesembiring@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '002347';
    $participant->name = 'Hendra';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281220180012';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'aa.rahen@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '001740';
    $participant->name = 'Arif Sri Nurcahyo';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281334582999';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'arifsri176@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '001741';
    $participant->name = 'Bayu Prihatnolo';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281330228407';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'bayou.bsyu@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '13008064';
    $participant->name = 'Erick Maranthona';
    $participant->unit_type = 'Ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628116442000';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'erick.potter89@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '11009432';
    $participant->name = 'Andrio Taulinno';
    $participant->unit_type = 'Ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628111104500';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'rioryu251211@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 9;
    $participant->nik = '10012516';
    $participant->name = 'Yohanes Apriandi Sianipar';
    $participant->unit_type = 'Ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628111830111';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'yohanessianipar85@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '13009733';
    $participant->name = 'Asep Muldani';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sumbagteng';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811760610';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'asepmuldaniii@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '12010148';
    $participant->name = 'Bobby Varyne Fernando';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sumbagsel';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '628117882121';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagsel';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'bobby_v_fernando_x@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '15008727';
    $participant->name = 'Reza Cahyaningrat';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Jabar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811232287';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'rezaviboy@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '14010262';
    $participant->name = 'Ahmad Ramdan';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Jabar';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285222990275';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'ahmadramdan3@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '10010154';
    $participant->name = 'M Irfan Marzuki';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Jatim';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281330345180';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'mochamad_i_marzuki_x@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '14012536';
    $participant->name = 'Mashuda R Luxmono';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Jateng';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6281326666210';
    $participant->gender = 'Male';
    $participant->region = 'Jateng';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'mashuda_r_luxmono_x@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '15009496';
    $participant->name = 'Heyder Paskah B Rombe';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sulawesi';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811494464';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'allanrombe92@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '71300';
    $participant->name = 'Joni F. Sinaga';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Sumbagut';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811657007';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'joni_f_sinaga@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '13008065';
    $participant->name = 'Ramos';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Headquarter';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285216111177';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'ramoz.saragih@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 8;
    $participant->nik = '14012962';
    $participant->name = 'Doddy Fahreza';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Headquarter';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '6285270636471';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'doddyfahreza26@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '69236';
    $participant->name = 'Daniel E. Saputro';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Balinusra';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '811100491';
    $participant->gender = 'Male';
    $participant->region = 'BaliNusra';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'daniel_e_saputro@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 13;
    $participant->nik = '74069';
    $participant->name = 'Eduardo SItumorang';
    $participant->unit_type = 'backendsupport';
    $participant->unit_name = 'Kalimantan';
    $participant->selection_date = '10/4/2016';
    $participant->mobile_phone = '62811199684';
    $participant->gender = 'Male';
    $participant->region = 'Kalimantan';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'edusitumorang1@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '13009331';
    $participant->name = 'Nixsi Erica Munte';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Batam Penuin';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811692127';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'nixsi.erica@yahoo.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '14010329';
    $participant->name = 'Pitri Rantawati';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Margo City';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628111160066';
    $participant->gender = 'Female';
    $participant->region = 'East Jakarta';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'pitrirantawati@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '15009481';
    $participant->name = 'Putri Elvirasari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Tasikmalaya';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281323351000';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'putri_elvirasari2_x@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '14011511';
    $participant->name = 'Jesyca M.B Wawolumaya';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Manado';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811435551';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'Jesyca.esy1992@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '14010071';
    $participant->name = 'Dewi Ayu Mulyasari';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Pontianak';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628115676869';
    $participant->gender = 'Female';
    $participant->region = 'Kalimantan';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'DEWIAYU.MLYSR@GMAIL.COM';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '16000588';
    $participant->name = 'Malasari Apriyanti';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Bandar Jaya';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285357009999';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagsel';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'malasari.apriyanti@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '10010534';
    $participant->name = 'Cindy Nastasia';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Kota Cirebon';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811240360';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'cindy.nastasia@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '13011386';
    $participant->name = 'Nur Kartika Prihatini';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Bangkalan';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281235558667';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'nurkartika.p@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '13008058';
    $participant->name = 'Inganita Pinem';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281396475023';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'inge.pinem@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '11011798';
    $participant->name = 'Monalisa Simanjuntak';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281376055014';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'mona.simanjuntak89@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '08009174';
    $participant->name = 'Machillah';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281230008684';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'chilla.estillo@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '13010341';
    $participant->name = 'Siti Asyiah';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6282336302580';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'sitia2889@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '10011212';
    $participant->name = 'Triwulandari';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285255447887';
    $participant->gender = 'Female';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'triwul.ndari@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '001690';
    $participant->name = 'Cici Kemala Sari Lubis';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811648348';
    $participant->gender = 'Female';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'lubis.cici@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '002827';
    $participant->name = 'Indra Wahyuningsih';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6282116344444';
    $participant->gender = 'Female';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'indra.wahyuningsih83@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '001756';
    $participant->name = 'Wuri Endah Lestari';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628113443444';
    $participant->gender = 'Female';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'wurie.lestari@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 5;
    $participant->nik = '12009764';
    $participant->name = 'Wulan Sari Romadona';
    $participant->unit_type = 'ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281319363802';
    $participant->gender = 'Female';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'fadilahdona@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '13010211';
    $participant->name = 'Randi Andaru Putra';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Mall SKA';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628117574491';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'randiandaru@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '12010327';
    $participant->name = 'Januar Putra';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Mataram';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811390113';
    $participant->gender = 'Male';
    $participant->region = 'BaliNusra';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'tl_mataram@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 10;
    $participant->nik = '14013222';
    $participant->name = 'Putu Anata Hary Sandy';
    $participant->unit_type = 'grapari';
    $participant->unit_name = 'Kuta';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628113977779';
    $participant->gender = 'Male';
    $participant->region = 'BaliNusra';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'hary05sandy@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '15008921';
    $participant->name = 'Nofirman Antoni';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Bukit Tinggi';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285376678585';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagteng';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'uda.anton@rocketmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '13009065';
    $participant->name = 'Muhammad Syamsudin';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Margo City';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628119999923';
    $participant->gender = 'Male';
    $participant->region = 'East Jakarta';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'isamchenko@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '16008685';
    $participant->name = 'Bayu Iwan Sugiyarto';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Tunjungan Plaza';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811360086';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'bayuiwansugiyarto@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '14008211';
    $participant->name = 'Mario Kelly Wenno';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Nabire';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285244828800';
    $participant->gender = 'Male';
    $participant->region = 'PapuaMaluku';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'rio.wenno@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 12;
    $participant->nik = '13011066';
    $participant->name = 'Muhammad Syuhri';
    $participant->unit_type = 'graparimitra';
    $participant->unit_name = 'Bone';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281242271576';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'suhry.akira@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '08010970';
    $participant->name = 'Sandi Hadiat';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281220523906';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'sandihadiat.7@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '005386';
    $participant->name = 'Taofan';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '62811220844';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'taofan.valen@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 6;
    $participant->nik = '15008213';
    $participant->name = 'Adriansyah';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285330660161';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'adriansyahccmksr@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '001675';
    $participant->name = 'Erwin Mangara Pasaribu';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Medan';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285270261777';
    $participant->gender = 'Male';
    $participant->region = 'Sumbagut';
    $participant->area = 1;
    $participant->judged = 0;
    $participant->email = 'erwin.m.pasaribu@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '10010232';
    $participant->name = 'Indra Gunawan';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Bandung';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281321651011';
    $participant->gender = 'Male';
    $participant->region = 'Jabar';
    $participant->area = 2;
    $participant->judged = 0;
    $participant->email = 'wchink1011@gmail.com ';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '11012628';
    $participant->name = 'Sigit Astiarso Nugroho';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Surabaya';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281332673767';
    $participant->gender = 'Male';
    $participant->region = 'Jatim';
    $participant->area = 3;
    $participant->judged = 0;
    $participant->email = 'sheget@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '10011428';
    $participant->name = 'Andi Irfan Kf';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628114198472';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'macbonecelebes83@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '10010377';
    $participant->name = 'Haeruddin';
    $participant->unit_type = 'CallCenter';
    $participant->unit_name = 'Makassar';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281394229974';
    $participant->gender = 'Male';
    $participant->region = 'Sulawesi';
    $participant->area = 4;
    $participant->judged = 0;
    $participant->email = 'haeruddin.udhink@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 14;
    $participant->nik = '09010575';
    $participant->name = 'Aries Anggoro';
    $participant->unit_type = 'ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628111435758';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'aries_anggoro_x@telkomsel.co.id';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 5;
    $participant->nik = '14011222';
    $participant->name = 'Yogi dhony saputro';
    $participant->unit_type = 'ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6281280997154';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'yogidhony100@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 5;
    $participant->nik = '15008061';
    $participant->name = 'Galang Mandala Putra';
    $participant->unit_type = 'ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628119199105';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'galangmp0@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 5;
    $participant->nik = '14012708';
    $participant->name = 'Andhika Dwi Putra';
    $participant->unit_type = 'ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '628111114662';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'andhika.dwiputra19@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);

    $participant = new User();
    $participant->category_id = 5;
    $participant->nik = '14013580';
    $participant->name = 'Putera Mahesa Kusumawardhana';
    $participant->unit_type = 'ecare';
    $participant->unit_name = 'Ecare';
    $participant->selection_date = '10/5/2016';
    $participant->mobile_phone = '6285333312263';
    $participant->gender = 'Male';
    $participant->region = 'Headquarter';
    $participant->area = 5;
    $participant->judged = 0;
    $participant->email = 'puteramahesa91@gmail.com';
    $participant->picture = 'picture.png';
    $participant->password = bcrypt('bestcsawards');
    $participant->birth_place = '';
    $participant->birthday = '';
    $participant->activated = 0;
	$participant->save();
	$participant->attachRole($participantRole);
    }
}
